---
- name: install node and npm
  hosts: ec2
  tasks:
    - name: Update apt repo
      apt: update_cache=yes force_apt_get=yes cache_valid_time=2400
    - name: Install nodejs and npm
      apt:
        pkg:
          - nodejs
          - npm

- name: Install acl
  hosts: ec2
  tasks:
    - name: Install acl
      apt:
        pkg:
          - acl

- name: Create new linux user for node app
  hosts: ec2
  vars_files:
    - ansible_vars
  tasks:
    - name: Create linux user
      user:
        name: "{{linux_name}}"
        comment: pavlo admin
        group: admin

- name: Deploy nodejs app
  hosts: ec2
  become: true
  become_user: "{{linux_name}}"
  vars_files:
    - ansible_vars
  tasks: 
    - name: Copy nodejs folder to a server
      unarchive:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}"
    - name: Install dependencies
      npm: 
        path: "{{user_home_dir}}/package"
    - name: Start nodejs app
      command: 
        chdir: /home/{{linux_name}}/package/app/
        cmd: node server
      async: 1000
      poll: 0
    - name: Make sure that app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


