---
- name: Configure nginx webserver
  hosts: ec2
  tasks:
  - name: uninstall nginx 
    apt: 
      name: nginx=1.18*
      state: absent
  - name: stop nginx 
    service:
      name: nginx
      state: started
